repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
# For Python files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
      - id: ruff-format
- repo: local
  hooks:
  - id: pytest-check
    stages: [commit]
    types: [python]
    name: pytest-check
    entry: poetry run pytest backend -v -rs -n auto --show-capture=no
    language: system
    pass_filenames: false
    always_run: true
